export const COUNTRIES = [
  "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan",
  "Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi",
  "Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo (Democratic Republic)","Congo (Republic)","Costa Rica","Côte d'Ivoire","Croatia","Cuba","Cyprus","Czech Republic",
  "Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia",
  "Fiji","Finland","France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana",
  "Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan",
  "Kazakhstan","Kenya","Kiribati","Kosovo","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg",
  "Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar",
  "Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","North Macedonia","Norway","Oman",
  "Pakistan","Palau","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russia","Rwanda",
  "Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","São Tomé and Príncipe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden","Switzerland","Syria",
  "Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu",
  "Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe",
] as const;

/** Portuguese (Portugal) names for the list above. The form always sends the English name, so the email and server checks do not change. */
export const COUNTRY_PT: Record<(typeof COUNTRIES)[number], string> = {
  "Afghanistan": "Afeganistão",
  "Albania": "Albânia",
  "Algeria": "Argélia",
  "Andorra": "Andorra",
  "Angola": "Angola",
  "Antigua and Barbuda": "Antígua e Barbuda",
  "Argentina": "Argentina",
  "Armenia": "Arménia",
  "Australia": "Austrália",
  "Austria": "Áustria",
  "Azerbaijan": "Azerbaijão",
  "Bahamas": "Baamas",
  "Bahrain": "Barém",
  "Bangladesh": "Bangladeche",
  "Barbados": "Barbados",
  "Belarus": "Bielorrússia",
  "Belgium": "Bélgica",
  "Belize": "Belize",
  "Benin": "Benim",
  "Bhutan": "Butão",
  "Bolivia": "Bolívia",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  "Botswana": "Botsuana",
  "Brazil": "Brasil",
  "Brunei": "Brunei",
  "Bulgaria": "Bulgária",
  "Burkina Faso": "Burquina Faso",
  "Burundi": "Burundi",
  "Cabo Verde": "Cabo Verde",
  "Cambodia": "Camboja",
  "Cameroon": "Camarões",
  "Canada": "Canadá",
  "Central African Republic": "República Centro-Africana",
  "Chad": "Chade",
  "Chile": "Chile",
  "China": "China",
  "Colombia": "Colômbia",
  "Comoros": "Comores",
  "Congo (Democratic Republic)": "Congo-Kinshasa",
  "Congo (Republic)": "Congo-Brazzaville",
  "Costa Rica": "Costa Rica",
  "Côte d'Ivoire": "Côte d’Ivoire (Costa do Marfim)",
  "Croatia": "Croácia",
  "Cuba": "Cuba",
  "Cyprus": "Chipre",
  "Czech Republic": "Chéquia",
  "Denmark": "Dinamarca",
  "Djibouti": "Jibuti",
  "Dominica": "Domínica",
  "Dominican Republic": "República Dominicana",
  "Ecuador": "Equador",
  "Egypt": "Egito",
  "El Salvador": "Salvador",
  "Equatorial Guinea": "Guiné Equatorial",
  "Eritrea": "Eritreia",
  "Estonia": "Estónia",
  "Eswatini": "Essuatíni",
  "Ethiopia": "Etiópia",
  "Fiji": "Fiji",
  "Finland": "Finlândia",
  "France": "França",
  "Gabon": "Gabão",
  "Gambia": "Gâmbia",
  "Georgia": "Geórgia",
  "Germany": "Alemanha",
  "Ghana": "Gana",
  "Greece": "Grécia",
  "Grenada": "Granada",
  "Guatemala": "Guatemala",
  "Guinea": "Guiné",
  "Guinea-Bissau": "Guiné-Bissau",
  "Guyana": "Guiana",
  "Haiti": "Haiti",
  "Honduras": "Honduras",
  "Hungary": "Hungria",
  "Iceland": "Islândia",
  "India": "Índia",
  "Indonesia": "Indonésia",
  "Iran": "Irão",
  "Iraq": "Iraque",
  "Ireland": "Irlanda",
  "Israel": "Israel",
  "Italy": "Itália",
  "Jamaica": "Jamaica",
  "Japan": "Japão",
  "Jordan": "Jordânia",
  "Kazakhstan": "Cazaquistão",
  "Kenya": "Quénia",
  "Kiribati": "Quiribáti",
  "Kosovo": "Kosovo",
  "Kuwait": "Koweit",
  "Kyrgyzstan": "Quirguistão",
  "Laos": "Laos",
  "Latvia": "Letónia",
  "Lebanon": "Líbano",
  "Lesotho": "Lesoto",
  "Liberia": "Libéria",
  "Libya": "Líbia",
  "Liechtenstein": "Listenstaine",
  "Lithuania": "Lituânia",
  "Luxembourg": "Luxemburgo",
  "Madagascar": "Madagáscar",
  "Malawi": "Maláui",
  "Malaysia": "Malásia",
  "Maldives": "Maldivas",
  "Mali": "Mali",
  "Malta": "Malta",
  "Marshall Islands": "Ilhas Marshall",
  "Mauritania": "Mauritânia",
  "Mauritius": "Maurícia",
  "Mexico": "México",
  "Micronesia": "Micronésia",
  "Moldova": "Moldávia",
  "Monaco": "Mónaco",
  "Mongolia": "Mongólia",
  "Montenegro": "Montenegro",
  "Morocco": "Marrocos",
  "Mozambique": "Moçambique",
  "Myanmar": "Mianmar (Birmânia)",
  "Namibia": "Namíbia",
  "Nauru": "Nauru",
  "Nepal": "Nepal",
  "Netherlands": "Países Baixos",
  "New Zealand": "Nova Zelândia",
  "Nicaragua": "Nicarágua",
  "Niger": "Níger",
  "Nigeria": "Nigéria",
  "North Korea": "Coreia do Norte",
  "North Macedonia": "Macedónia do Norte",
  "Norway": "Noruega",
  "Oman": "Omã",
  "Pakistan": "Paquistão",
  "Palau": "Palau",
  "Palestine": "Territórios palestinianos",
  "Panama": "Panamá",
  "Papua New Guinea": "Papua-Nova Guiné",
  "Paraguay": "Paraguai",
  "Peru": "Peru",
  "Philippines": "Filipinas",
  "Poland": "Polónia",
  "Portugal": "Portugal",
  "Qatar": "Catar",
  "Romania": "Roménia",
  "Russia": "Rússia",
  "Rwanda": "Ruanda",
  "Saint Kitts and Nevis": "São Cristóvão e Neves",
  "Saint Lucia": "Santa Lúcia",
  "Saint Vincent and the Grenadines": "São Vicente e Granadinas",
  "Samoa": "Samoa",
  "San Marino": "São Marinho",
  "São Tomé and Príncipe": "São Tomé e Príncipe",
  "Saudi Arabia": "Arábia Saudita",
  "Senegal": "Senegal",
  "Serbia": "Sérvia",
  "Seychelles": "Seicheles",
  "Sierra Leone": "Serra Leoa",
  "Singapore": "Singapura",
  "Slovakia": "Eslováquia",
  "Slovenia": "Eslovénia",
  "Solomon Islands": "Ilhas Salomão",
  "Somalia": "Somália",
  "South Africa": "África do Sul",
  "South Korea": "Coreia do Sul",
  "South Sudan": "Sudão do Sul",
  "Spain": "Espanha",
  "Sri Lanka": "Sri Lanca",
  "Sudan": "Sudão",
  "Suriname": "Suriname",
  "Sweden": "Suécia",
  "Switzerland": "Suíça",
  "Syria": "Síria",
  "Taiwan": "Taiwan",
  "Tajikistan": "Tajiquistão",
  "Tanzania": "Tanzânia",
  "Thailand": "Tailândia",
  "Timor-Leste": "Timor-Leste",
  "Togo": "Togo",
  "Tonga": "Tonga",
  "Trinidad and Tobago": "Trindade e Tobago",
  "Tunisia": "Tunísia",
  "Turkey": "Turquia",
  "Turkmenistan": "Turquemenistão",
  "Tuvalu": "Tuvalu",
  "Uganda": "Uganda",
  "Ukraine": "Ucrânia",
  "United Arab Emirates": "Emirados Árabes Unidos",
  "United Kingdom": "Reino Unido",
  "United States": "Estados Unidos",
  "Uruguay": "Uruguai",
  "Uzbekistan": "Usbequistão",
  "Vanuatu": "Vanuatu",
  "Vatican City": "Cidade do Vaticano",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietname",
  "Yemen": "Iémen",
  "Zambia": "Zâmbia",
  "Zimbabwe": "Zimbabué",
};

export function countryOptions(lang: "en" | "pt"): { value: string; label: string }[] {
  const list = COUNTRIES.map((c) => ({ value: c as string, label: lang === "pt" ? COUNTRY_PT[c] : c }));
  return lang === "pt" ? list.sort((a, b) => a.label.localeCompare(b.label, "pt-PT")) : list;
}
